apiVersion: batch/v1
kind: CronJob
metadata:
  name: architect-python-batch-job
  namespace: default
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: telemetry-batch-processor
        spec:
          containers:
          - name: telemetry-batch-processor
            image: python:3.11-slim
            imagePullPolicy: IfNotPresent
            command: ["python", "-c", "import os; print('=== ENTORNO INICIADO CORRECTAMENTE ==='); print('AWS ID:', os.environ.get('AWS_ACCESS_KEY_ID'))"]
            env:
            - name: AWS_ACCESS_KEY_ID
              value: "mock_key"
            - name: AWS_SECRET_ACCESS_KEY
              value: "mock_secret"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ENDPOINT_URL
              value: "http://host.docker.internal:4566"
            - name: SIMULATION_MODE
              value: "OFF"
          restartPolicy: OnFailure