name: CI/CD Pipeline - Next 3

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ejecutar pruebas unitarias (CI)
        run: |
          python -m pip install --upgrade pip
          pip install -r containers/ninth_container/repaso/next_3/requirements.txt
          PYTHONPATH=containers/ninth_container/repaso/next_3 pytest containers/ninth_container/repaso/next_3/tests

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir y publicar imagen (CD)
        uses: docker/build-push-action@v5
        with:
          context: ./containers/ninth_container/repaso/next_3
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/engine-s3-service:latest
