apiVersion: v1
kind: Pod
metadata:
  name: python-batch-pod
  labels:
    component: architect-python-batch
    layer: exercise-1
spec:
  restartPolicy: Never
  containers:
  - name: python-worker
    image: python:3.10-slim
    # Ejecutamos el archivo que montamos en la carpeta /app
    command: ["python", "/app/app.py"]
    
    # El eje inferior izquierdo de la X: Inyección de variables de entorno
    env:
    - name: BATCH_NAME
      value: "Lote-Kubernetes-ConfigMap"
    - name: TOTAL_ITEMS
      value: "7"
      
    # Montamos el volumen en el sistema de archivos del contenedor
    volumeMounts:
    - name: script-volume
      mountPath: /app
  
  # Declaramos el volumen apuntando al ConfigMap
  volumes:
  - name: script-volume
    configMap:
      name: python-script-config
