apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-eficiente-batch
  namespace: default
spec:
  schedule: "*/5 * * * *" # <-- ¡Aquí está la única pieza nueva! Cada 5 minutos.
  concurrencyPolicy: Forbid # <-- Si un proceso se traba, prohíbe que se encime el siguiente.
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: python-worker
            image: python:3.10-slim
            command: ["python", "/app/procesador.py"]
            env:
            - name: APP_ENV
              value: "Produccion-Costos-Bajos"
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "200m"
            volumeMounts:
            - name: espacio-codigo
              mountPath: /app
          volumes:
          - name: espacio-codigo
            configMap:
              name: procesador-config
