name: 🚀 CI/CD - Full Pipeline (Test & Docker Hub Push)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  # ==========================================
  # JOB 1: INTEGRACIÓN CONTINUA (TESTING)
  # ==========================================
  python-tests:
    name: 🧪 Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Checkout del código
        uses: actions/checkout@v4

      - name: 2️⃣ Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 3️⃣ Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4️⃣ Ejecutar Pytest
        run: |
          pytest tests/

  # ==========================================
  # JOB 2: DESPLIEGUE CONTINUO (DOCKER HUB)
  # ==========================================
  docker-build-push:
    name: 🐳 Build & Push Docker Image
    needs: python-tests
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Checkout del código
        uses: actions/checkout@v4

      - name: 2️⃣ Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 3️⃣ Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 4️⃣ Compilar y Subir Imagen a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fleet-telemetry-processor:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fleet-telemetry-processor:${{ github.sha }}
