version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-s3-vault
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  web-app:
    image: leopinzon75/diagnostic-vault-app:latest
    container_name: diagnostic-flask-app
    ports:
      - "5000:5000"
    environment:
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minio_admin
      - AWS_SECRET_ACCESS_KEY=minio_password
    depends_on:
      minio:
        condition: service_healthy
