apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-taller-compartido
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual # <-- Le ponemos una etiqueta a la toma de pared
  hostPath:
    path: /run/desktop/mnt/host/wsl/datos_profesionales
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-herramienta-python
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual # <-- Obligamos a la manguera a buscar solo la toma "manual"
  resources:
    requests:
      storage: 1Gi
