worker_processes 1;

events {
    worker_connections 1024;
}

http {
    lua_package_path "/usr/local/openresty/nginx/lua/?.lua;;";
    lua_shared_dict limiter_storage 10m; # Aquí vive nuestra tabla de Hash O(1)

    server {
        listen 8080;
        server_name localhost;
        lua_code_cache off;

        location /api {
            # Definimos variables dinámicas nativas de Nginx que Lua va a leer
            set $limit_bucket_capacity 5;  # Capacidad del balde
            set $limit_refill_rate 2;      # Tokens por segundo

            content_by_lua_block {
                package.loaded["rate_limiter"] = nil
                local limiter = require "rate_limiter"
                
                -- Le pasamos las variables dinámicas al plugin
                limiter.check_rate(ngx.var.limit_bucket_capacity, ngx.var.limit_refill_rate)
                
                ngx.status = ngx.HTTP_OK
                ngx.header.content_type = "application/json; charset=utf-8"
                ngx.say([[{"status": "success", "message": "Petición procesada: Tráfico limpio a través del Gateway"}]] )
            }
        }
    }
}
