version: '3.8'

services:
  telemetry-pipeline:
    build: .
    image: leopinzon75/telemetry-pipeline:v1.0
    container_name: fleet_telemetry_app
    env_file:
      - .env
    volumes:
      - ./data:/app/data
