version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.3.2
    container_name: localstack_simulador
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 3s
      timeout: 3s
      retries: 5

  fleet-worker:
    build: .
    image: fleet-multicloud-worker:local
    container_name: fleet_batch_worker_instance
    environment:
      - SIMULACION=False
      - AWS_INPUT_BUCKET=dev-fleet-raw-data
      - AWS_INPUT_KEY=daily_telemetry.csv
      - AZURE_OUTPUT_CONTAINER=dev-fleet-alerts
      - AWS_ACCESS_KEY_ID=mock_key_para_pruebas_locales
      - AWS_SECRET_ACCESS_KEY=mock_secret_para_pruebas_locales
      - AWS_ENDPOINT_URL=http://localstack:4566
    volumes:
      - ./data:/app/data
    depends_on:
      localstack:
        condition: service_healthy

  scheduler:
    image: mcuadros/ofelia:latest
    container_name: local_cloud_scheduler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: daemon --docker
    labels:
      ofelia.job-run.fleet-batch-trigger.schedule: "*/1 * * * *"
      ofelia.job-run.fleet-batch-trigger.container: "fleet_batch_worker_instance"
